version: '3.9'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  nginx:
    build:
        context: ./
        dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - '8080:80'
    depends_on:
      - php-fpm
  php-fpm:
    image: php:7.4.33-fpm-alpine3.16
    env_file:
      - '.env'
    volumes:
      - ./:/var/www/html
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
